# NumPy

* NumPy yra tiesinės algebros biblioteka. Jos pagrindu sukurtos beveik visos su duomenų mokslu susijusios bibliotekos, tokios kaip Pandas ir kt. Numpy yra itin greita, nes yra susieta ryšiais(bindings) su C kalba parašytais moduliais. 

* Standartiškai įsidiegia *pip install numpy*, jeigu naudojate Anaconda - *conda install numpy*
* Dažniausiai naudojamas NumPy ingredientas - NumPy masyvai. Jie būna dviejų tipų - vektoriai ir matricos.  

Prieš pradedant darbą su NumPy, reikia jį importuoti.

In [5]:
import numpy as np

tarkime, turime paprastą Python list'ą:

In [6]:
listas = [1, 2, 3, 4, 5]

paveskime jį į NumPy array:

In [7]:
arr = np.array(listas)

In [8]:
arr

array([1, 2, 3, 4, 5])

gauname 1 lygio NumPy masyvą (vektorių). Jeigu norime matricos, turime sukurti keletą masyvų masyve:

In [9]:
mano_listai = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
matrica = np.array(mano_listai)


In [10]:
matrica

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

NumPy turi ir integruotus, paprastus būdus susikurti masyvą. Skliausteliuose reikia įrašyti start, stop ir step(nebūtina) reikšmes:

In [11]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

jeigu reikia vektoriaus iš nulių:

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

jeigu matricos iš nulių:

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Analogiškai veikia np.ones metodas.
Dar viena naudinga funkcija - linspace. Ji grąžina masyvą, su lygiais intervalais išdėliotomis reikšmėmis. Reikia nurodyti start, stop ir intervalo reikšmes:

In [ ]:
np.linspace(0,20,16)

Jeigu prireikė vienetinės matricos:

In [ ]:
np.eye(6)

# Random arrays kūrimas

Pirmas metodas susikurti random array - **np.random.rand()**. Jo pagalba galime susikurti masyvą su atsitiktinėm reikšmėm nuo 0 iki 1 *("uniform" distribution)*

In [ ]:
np.random.rand(10)

jeigu norime ne vektoriaus, o matricos:

In [ ]:
np.random.rand(5,5)

**np.random.randn()** sugeneruos reikšmes iš  *“standard normal” distribution* (standartinis normalusis skirstinys)

In [ ]:
np.random.randn(3,3)

**np.random.randint()** sugeneruoja atsitiktines integer reikšmes. Parametruose reikia nurodyti, žemiausią, aukščiausią (neįskaitant) reikšmes ir norimą kiekį reikšmių.

In [ ]:
np.random.randint(100, 200, 20)

# Masyvų pertvarkymas

**reshape()** metodas leidžia mums performuoti turimą masyvą į kitą formą:

In [ ]:
my_array = np.random.randint(0, 100, 64)

In [ ]:
my_array

In [ ]:
reshaped_array = my_array.reshape(8,8)

In [ ]:
reshaped_array

šiame pavyzdyje vektorių iš 64 reikšmių performavome į 8x8 matricą.

# Naudingi Metodai

**max()** ir **.min()** metodai ištraukia maksimalią ir minimalią reikšmes iš masyvo:

In [ ]:
my_array.min()

In [ ]:
my_array.max()

**argmax()** ir **argmin()** nurodo mums maksimalios ir minimalios reikšmių indeksą:

In [ ]:
my_array.argmax()

In [ ]:
my_array.argmin()

**.shape** nurodo, kokią formą turi mūsų masyvas:

In [ ]:
reshaped_array.shape

**.dtype** nurodo, koks duomenų tipas yra mūsų masyve:

In [ ]:
reshaped_array.dtype

# Indeksacija ir reikšmių traukimas

In [ ]:
sample_array = np.arange(1,10)

In [ ]:
sample_array

reikšmę iš vektoriaus traukiame taip pat kaip ir iš Python sąrašo:

In [ ]:
sample_array[5]

galime naudoti *slices*:

In [ ]:
sample_array[2:8]

In [ ]:
sample_array[6:]

In [ ]:
sample_array[-5:]

galime pasirinktam rėžiui suteikti kokią nors savo reikšmę *(Broadcasting)*: 

In [ ]:
sample_array[4:8] = 50

In [ ]:
sample_array

# Reikšmių traukimas iš matricos 

In [ ]:
sample = np.random.randint(1, 10, 25)

In [ ]:
sample_matrix = sample.reshape(5,5)

In [ ]:
sample_matrix

In [ ]:
sample_matrix[2,2] 

laužtiniuose skliausteliuose pirmiau nurodome eilutę, paskui tos eilutės nario indeksą.

taip pat galime naudoti rėžius:

In [ ]:
sample_matrix[1:4, 1:4]

In [ ]:
sample_matrix[3:,:]

In [ ]:
sample_matrix[:, 0:2]

# Reikšmių traukimas pagal sąlygą

Tarkime, turime masyvą:

In [ ]:
masyvas = np.arange(1,21)

In [ ]:
masyvas

norime reikšmių, didesnių už 9:

In [ ]:
bool_masyvas = masyvas > 9

In [ ]:
bool_masyvas

gauname masyvą iš *bool* reikšmių, kuriame True reikšmės atitinka užduotą sąlygą. Atlikime tokią operaciją:

In [ ]:
masyvas[bool_masyvas]

kintamojo *masvas* laužtiniuose skliautuose įvedę kintamąjį *bool_masyvas*, gauname reikšmes, kurios atitinka True indeksą. Tą patį rezultatą galime gauti laužtiniuose skliaustuose tiesiog įrašę sąlygą:

In [ ]:
masyvas[masyvas>9]

# Numpy elgsenos ypatumai

Yra tam tikri NumPy elgsenos ypatumai, tarkime:

In [ ]:
pvz = np.random.randint(1, 21, 20)

In [ ]:
pvz

turime *random* masyvą iš integer reikšmių. Susikurkime jo atraižą:

In [ ]:
pvz_ispjova = pvz[5:15]

In [ ]:
pvz_ispjova

In [ ]:
pvz_ispjova[:] = 99

In [ ]:
pvz_ispjova

Iki šio momento viskas atrodo kaip ir tikėtąsi. Tačiau išsikvietę pirmąjį masyvą matome:

In [ ]:
pvz

Paprastai kuriant kintamąjį, užkulisiuose padaroma kopija šaltinio, iš kurio jis gaminamas (šiuo atveju *pvz*). 
Iš tos kopijos formuojamas naujas kintamasis. Tačiau NumPy atveju pakeitimai vykdomi originale, ir mums 
rodoma tik modifikuota to originalo dalis. NumPy pritaikytas darbui su milžiniškais kiekiais duomenų. Daryti laikinas jų kopijas atmintyje yra neefektyvu, ir nestabilu. Todėl, kai norime išsaugoti originalą, turime nurodyti, kad norėsime pasidaryti kopiją:

In [ ]:
pvz_copy = pvz.copy()

In [ ]:
pvz_copy

In [ ]:
pvz_copy == pvz

In [ ]:
pvz_copy_ispjova = pvz_copy[5:15]
pvz_copy_ispjova[:] = 100

In [ ]:
pvz_copy_ispjova

In [ ]:
pvz

In [ ]:
pvz_copy

Taigi, pasidarėme kopiją, nurodėme kad norime jos rėžio [5:15] kintamąjame *pvz_copy_ispjova*, joje visas reikšmes pakeitėme į 100, ir įsitikinome, kad po to originalusis *pvz* liko nepakeistas.

# Matematinės operacijos ir funkcijos

su NumPy arrays galima atlikti paprastus aritmetinius veiksmus:

In [ ]:
vektorius = np.arange(1,11)

In [ ]:
vektorius

In [ ]:
vektorius + vektorius

In [ ]:
vektorius * vektorius

In [ ]:
vektorius / vektorius

In [ ]:
vektorius / 0

atkreipkite dėmesį, atlikus dalybą iš 0 gausime begalybes arba nan - not a number. Taip pat galime atlikti veiksmus ir su skaičiais:

In [ ]:
vektorius + 1000

In [ ]:
vektorius ** 3

ir t.t.

Numpy aplinkoje taip pat galime taikyti įvairias trigonometrines funkcijas ir tt.

In [ ]:
np.sin(vektorius)

In [ ]:
np.log(vektorius)

Visas matematines funkcijas galite surasti
[čia](https://docs.scipy.org/doc/numpy/reference/ufuncs.html).